CREATE TABLE R_MEMBER_GROUP (
    MEMBER_ID           varchar(20) NOT NULL,
    MEMBER_GROUP_ID     varchar(20) NOT NULL,
    PRIMARY KEY (MEMBER_ID, MEMBER_GROUP_ID)
)    ENGINE=InnoDB DEFAULT CHARSET=utf8
;